name: Connect EKS
description: >-
  Connect to Tailscale VPN, assume AWS role, and update KubeConfig to connect to EKS cluster

inputs:
  aws-region:
    description: The AWS region where the EKS cluster is located
    required: true
  aws-role-arn:
    description: The ARN of the AWS role to assume
    required: true
  aws-role-session-name:
    description: The name of the AWS role session
    required: true
  cluster-name:
    description: The name of the EKS cluster
    required: true
  tailscale-authkey:
    description: The Tailscale auth key
    required: false
    default: ''
  tailscale-oauth-client-id:
    description: The Tailscale OAuth client ID
    required: false
    default: ''
  tailscale-oauth-secret:
    description: The Tailscale OAuth client secret
    required: false
    default: ''
  tailscale-tags:
    description: The Tailscale tags to use
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Connect to Tailscale
      # https://github.com/tailscale/github-action
      uses: tailscale/github-action@6cae46e2d796f265265cfcf628b72a32b4d7cade # v3.3.0
      with:
        authkey: ${{ inputs.tailscale-authkey }}
        oauth-client-id: ${{ inputs.tailscale-oauth-client-id }}
        oauth-secret: ${{ inputs.tailscale-oauth-secret }}
        tags: ${{ inputs.tailscale-tags }}
        version: latest

    - name: Configure AWS credentials
      # https://github.com/aws-actions/configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: ${{ inputs.aws-role-session-name }}

    - name: Update Kubeconfig
      shell: bash
      run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        REGION: ${{ inputs.aws-region }}
